### ISSUE TITLE
Finish course when end is reached

### ISSUE THREAD

**Issue by ibooij** [ibooij/big-ring#11]
Currently, the simulation just keeps chugging on, even after reaching the end of a course or even a video. 

Change this to:
* if the end of course is reached, show the option to contine, but also to stop.
* if the end of the video is reached, show this and let the user go back to the course selection window.

**Comment by pajakgdynia** [comment]
There is a better way: if course finishes, just show message panel with information "End of route".

**Comment by ibooij** [comment]
First implementation in b2d072fc18c8949f6e7ec6d3dd9cb3f0579baff1. This just pops up a dialog which states that the course is finished. Will be better to use a message panel (see #25) and let the rider continue.

**Comment by ibooij** [comment]
Made a better implementation, which is more like @pajakgdynia proposed. It just shows the rider that the course is finished using a message panel. After 10 seconds the panel disappears. Meanwhile, the rider can just continue riding for his/her cooling down. Fix not on master yet.

**Comment by ibooij** [comment]
Fixed in 24a3bca1d9eeb6607e3ac2b81cc371ae33432c17
