### ISSUE TITLE
Support gpx files

### ISSUE THREAD

**Issue by ibooij** [ibooij/big-ring#15]
Currently, only (Tacx) rlv & pgmf files are supported as meta-data formats. 

It would be good to also support gpx files. Then it would be a lot easier to support user created content.

part of a relevant .gpx file (Hahtennjoch):

```xml
<gpx xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.1" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd" creator="RoadMovieCreator" xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
 <trk>
  <trkseg>
   <trkpt lat="47.3253240064" lon="10.5277110357">
    <ele>972.7999877930</ele>
    <time>2014-09-29T17:24:46.000+00:00</time>
    <speed>8.93102</speed>
    <extensions>
     <mediatime>00:00:00.000</mediatime>
    </extensions>
   </trkpt>
   <trkpt lat="47.3253741302" lon="10.5278036557">
    <ele>972.7999877930</ele>
    <time>2014-09-29T17:24:47.000+00:00</time>
    <speed>8.93102</speed>
    <extensions>
     <mediatime>00:00:01.000</mediatime>
    </extensions>
   </trkpt>
```

The `<mediatime>` tag is an extension. If the video and gpx file are synchronized then it won't be needed.

**Comment by pajakgdynia** [comment]
Other formats (especially .tts and CycleOps .xml) are quite often used.
Contact me, please.

**Comment by ibooij** [comment]
Supporting .tts files will probably be complicated. From what I know, these files are encrypted binary files, so we would have to be able to decrypt the files and after that also understand the binary encoding.

For Cycleops Virtual Training files, I created issue #19.

**Comment by ibooij** [comment]
Working version is in b7151a2d839d (on branch support_gpx_files)
