### ISSUE TITLE
Profile panel extension

### ISSUE THREAD

**Issue by pajakgdynia** [ibooij/big-ring#22]
In the profile panel there should be available:
- showing selected course range in color, other parts (before and after) shall be gray
- showing given range (not always whole)
- showing vertical line (with icon), useful for showing current position, POIs and opponent positions

Handling mouse actions in "course selection". Left-click select position (if within current course): shows vertical line and screenshot/position on the map for selected position. Additional checkbox used to show whole route/selected course.

In "course definition", there should be available range selection. Selected position is shown in video panel. Begin/End buttons to select course range (gray!). Zoom +/- buttons would be nice, as well as slider to scroll zoomed pixmap.

**Comment by ibooij** [comment]
If I understand correctly, the first part is an enhancement of the profile panel as shown during a ride. The second an enhancement of the course selection gui. Am I right? If so, I'd like to split these into two issues, which would make it easier to track the progress of these issues.

**Comment by pajakgdynia** [comment]
First part is the list of changes to be done in the common code (profile drawing).
2nd and 3rd paragraph concern particular usages, so it seems the issue can be split into three.

**Comment by ibooij** [comment]
Partial fix in 24a3bca1d9eeb6607e3ac2b81cc371ae33432c17. Distance and altitudes are now shown.

**Comment by ibooij** [comment]
Will be trying to make a zoomed in profile (current km/mile), #63 . Closing this issue
