### ISSUE TITLE
Route length

### ISSUE THREAD

**Issue by pajakgdynia** [ibooij/big-ring#23]
Course cannot be longer than whole route..

(Unfortunately, gitHub doesn't support RLV file type.. 'Xorret del CAti' doesn't work properly)

**Comment by ibooij** [comment]
partial fix in 8230ec0a005.

Still need to filter out courses that are longer than the whole route. On the other hand, perhaps "Garbage In = Garbage out" is not too bad a principle.

**Comment by ibooij** [comment]
Closing this now, as I don't think it's very important to support videos with faulty data at this moment.
