### ISSUE TITLE
HD video thumbnails drops core

### ISSUE THREAD

**Issue by pajakgdynia** [ibooij/big-ring#27]
FullHD and 4K videos drop core when route is selected: preview cannot be built properly.
ThumbnailCreatingVideoReader::createImage() @memcopy().

(My display resolution is 1280x800, does it make any difference?)

**Comment by ibooij** [comment]
Your resolution should not make a difference.

I tried it on Linux with a "random" (non-cycling) 4k video that I could download. It worked ok. Would you be able to make (a part of) the video with which you have the problem available. Perhaps put in on Dropbox or something like that so I can download it and try it here?

**Comment by pajakgdynia** [comment]
The issue I've found is in SK_GdL2014 and another 4K video (Suzie, but I cannot tell anything more about it).
I checked other 4K/FullHD videos: they work. It is not a problem with resolution/etc.
In front of these files there are 'D' frames which cannot be decoded properly or are empty (no matter).

I think that first "visible" frame shall be shown in the preview. I'll take a look on it.

**Comment by pajakgdynia** [comment]
I did some more investigations with SK_GdL2014. Terrible video, size 9gigs,
quality is very low (everything has own ghosts..), strange 'D' frames, a
lot of jukn at the end..

Small correction in creating thumbnail (checking size of the decoded frame)
hides the problem (this is, app don't stop, but still no picture).

The main reason is.. libAV cannot read non-key frames after seek operation
(I'll check exactly what does it mean..). So loadNextFrame() must be
"improved" a bit, or nothing more than "end of file reached" in the log
you'll see.. Seeking (both directions..) is necessary.

The second thing.. If video is shown with very high rate, some frames have
to be dropped. The same apply to broken video and ones with these 'D'
frames (it seams, that 'D' frames are not read by libAV at all.. 'D' means
deprecated? :) ) VideoPlayer must handle such situations properly.

I've done first "coding-tests". At least video shows up (even GdL). But
there is too many buffers and frame numbers, and I haven't managed to
handle them properly (to keep video in sync with route). I think.. one more
evening will help :)

Best regards,
Jarek.

**Comment by ibooij** [comment]
About the frame dropping with when we need higher frame rates, needed when virtual speed is higher than camera recording speed: That is already in the software. The frames still have to be decoded, but they are not copied to OpenGL mapped memory. We have to decode them, because otherwise there would be artifacts in the video.

Could you point out what you changed in loadNextFrame()? I know that it is not ready yet, but I'm interested to see what you did to at least keep it from crashing.

**Comment by pajakgdynia** [comment]
QImage ThumbnailCreatingVideoReader::createImage()

{

    AVFrame *frame = frameYuv().frame;

    QImage image(frame->width, frame->height, QImage::Format_RGB888);

    if (frame->width * frame->height) {

        sws_scale(_swsContext,

                  frame->data, frame->linesize, 0, codecContext()->height,

                  _frameRgb->frame->data, _frameRgb->frame->linesize);

        std::memcpy(image.bits(), _frameRgb->frame->data[0],
_imageBuffer.size());

    }

    return image;

}


Thus is.. if not picture exists, then empty image is returned.

This only solves core-condition (thus can be left in the code), but
changing the videoReader behaviour is necessary (preliminary "development"
solution):

    while (!frameFinished) {

        if (_targetFrame >= 0) {

            qDebug() << "seeking to" << _targetFrame;

            if (av_seek_frame(formatContext(), _currentVideoStream,
_targetFrame,

                          AVSEEK_FLAG_FRAME | AVSEEK_FLAG_BACKWARD) < 0) {

                qDebug() << "cannot seek to " << _targetFrame;

                _targetFrame = -1;

                return -1;

            }

            avcodec_flush_buffers(codecContext());

        }

        if (av_read_frame(formatContext(), &packet) < 0) {

            // if cannot read the frame after seek..

            // this is not K frame, and previous one must be checked

            // BUG in libAV: cannot read not-K frame after seek

            if (_targetFrame >= 0) {

                _targetFrame++;

                qDebug() << "check next frame " << _targetFrame << " if key";

                skipedFrames++;

                continue;

            } else {

                qDebug() << "cannot read frame";

                return -1;

            }

        } else {

            if (_targetFrame >= 0) {

                qDebug() << "Frame " << _targetFrame << " read, " <<
skipedFrames << " skipped";

                _targetFrame = -1;

            }

        }


_targetFrame is class field, set in performSeek(). There is forward seeking
only. It still doesn't work too often (somehow frames aren't read
properly.. even if they should).

**Comment by ibooij** [comment]
I have downloaded that same video. The behavior is not right indeed. 

I don't want to put in fixes with seeking etc before we really know what is going on. The fix for crashing is important to put in, so I'll do that.

**Comment by ibooij** [comment]
Made new issue #28 for the weird behaviour, closing this issue, because the crash does not occur anymore.
