### ISSUE TITLE
Distance to frame computation

### ISSUE THREAD

**Issue by pajakgdynia** [ibooij/big-ring#30]
findDistanceMappingEntryFor(distance) works incorrectly when any distance smaller than last found is requested, "rewinding" doesn't work properly

**Comment by ibooij** [comment]
Can you point out what exactly doesn't work?

There is a test in the test/ directory, VirtualTrainingFileParserTest. If, in the testWithBavellaFile() method, I change this:

```cpp
QCOMPARE(rlv.frameForDistance(0.0f), 0u);
QCOMPARE(tacxRlv.frameForDistance(0.0f), 0u);
QCOMPARE(rlv.frameForDistance(332.8), 
QCOMPARE(tacxRlv.frameForDistance(332.8), 1000u);
```

to this:

```cpp
QCOMPARE(rlv.frameForDistance(332.8), 
QCOMPARE(tacxRlv.frameForDistance(332.8), 1000u);
QCOMPARE(rlv.frameForDistance(0.0f), 0u);
QCOMPARE(tacxRlv.frameForDistance(0.0f), 0u);
```

things still work. Or is this not what you are saying here?

**Comment by pajakgdynia** [comment]
The problem was that rewind was not working correctly. Sometimes videos was incorrectly positioned (distance was calculated basing on the last found DistanceMappingEntry).
When video is started, frame numbers are logged.. and therefore starting frame was computed incorrectly (for DE_Bienstaedt, "future" one was shown, something around 32:00 instead 28:10).
I will see what about the tests as well.
BTW, I have already corrected it in my feature/sync_video branch..

**Comment by ibooij** [comment]
This has been fixed by adding a special class (template) for distance to frame/slope, which allows to search backwards.
