### ISSUE TITLE
Storing training results

### ISSUE THREAD

**Issue by pajakgdynia** [ibooij/big-ring#32]
Training results should be stored in a file, which can be imported by external software (eg. GoldenCheetah) for analysis.
Garmin's .tcx suits requirements well. It is a bit verbose ("extensions" tags).. but is clearly readable.

**Comment by ibooij** [comment]
If we're targeting GoldenCheetah, then their json format is very easily exported to. Tcx would take some more work, but seems doable.

**Comment by ibooij** [comment]
Tcx export merged to master in a399d5739a4df5c82e9553349e3946f46a496737
