### ISSUE TITLE
Not all frames are played

### ISSUE THREAD

**Issue by pajakgdynia** [ibooij/big-ring#42]
When video is recorded with (relatively) high framerate, some frames are not played.
If framerate in .rlv file is 25, and video is 50fps, only every second frame is shown, and video is a bit jerky.
Worse (can be) gpx files: when framerate (in the code) is changed to 1..

**Comment by ibooij** [comment]
The simulation is run every 1/50th of a second, after which the distance for the video player is set, this should, in theory, not put a limit on which frames from a 50fps video are played. Unless I am mistaken of course. Mind you, this would only work with the (read: your) new video player which is not on master yet.

Or is there another issue?

**Comment by pajakgdynia** [comment]
I was sleeping.. The issue is related to casting from double to int, and vice versa..
Close it, please..

**Comment by ibooij** [comment]
No problem, thanks for the update.
