### ISSUE TITLE
Videos with gliches

### ISSUE THREAD

**Issue by pajakgdynia** [ibooij/big-ring#45]
* TacX/T1956.44-FR_Hell of the North/F_Roubaix.avi
Video has non-standard size (1954x640) and thumbnails are wrong (black&white, lines are shifted to the left, merier then closer the bottom).
Do other high-res videos work properly?

* TacX/ES_MajorcaDemo/ES_MajorcaDemo.avi
In .rlv files (pgmf?) olnly 1 frame of length 0.578704 is defined (@fps 24). Route is 4003.47 and 6972 frames @22
All these corrections must be checked together..
Many (especially "older") videos have "only 1 frame" issue..

* TacX/T1956.07-FR_Aube Valley Ride/FR_Aube-Valley.avi
.rlv has 30726 frames, while video 194565. Distance differs as well (12815.3 vs 78106)

**Comment by ibooij** [comment]
> TacX/T1956.44-FR_Hell of the North/F_Roubaix.avi
> Video has non-standard size (1954x640) and thumbnails are wrong (black&white, lines are shifted to the left, merier then closer the bottom).
> Do other high-res videos work properly?

I have a couple of High resolution videos (1920x1080). These all work fine. This might have something to do with line sizes of video that are not properly read or handled.
I don't have this one or any other with the same resolution.

> 
> TacX/ES_MajorcaDemo/ES_MajorcaDemo.avi
> In .rlv files (pgmf?) olnly 1 frame of length 0.578704 is defined (@fps 24). Route is 4003.47 and 6972 frames @22
> All these corrections must be checked together..
> Many (especially "older") videos have "only 1 frame" issue..

The ES_MajorcaTour video has the same thing. It does work OK. The sync is correct (in the code that is in git master).

> 
> TacX/T1956.07-FR_Aube Valley Ride/FR_Aube-Valley.avi
> .rlv has 30726 frames, while video 194565. Distance differs as well (12815.3 vs 78106)

I don't have this one, so I have no idea.

**Comment by fps** [comment]
Oh drats, I knew my username would someday bite me in the butt :)

**Comment by ibooij** [comment]
@fps Glad to be of service! It just had to happen some day.

**Comment by ibooij** [comment]
Don't know what to do with this now. 

If more notifications of videos that don't work come in, we'll open a new case.
