### ISSUE TITLE
Add option to set maximum percentage of climb

### ISSUE THREAD

**Issue by ibooij** [ibooij/big-ring#52]
This is the 'save your knees' option. Speed should still be calculated with the actual percentage, but a smart trainer should put the load any higher than this percentage.

**Comment by pajakgdynia** [comment]
Slope should (in the profile) should be limited to this value as well (and everything "above" should be shown in "highest" color).
It will solve problems with .gpx routes, where slope might be extremely high (and thus whole profile is "green").
The same for "downhill" bounds.

**Comment by ibooij** [comment]
Currently implemented only as a maximum and minimum for smart trainers. The slope values sent to the trainer will be limited by the values set. Simulation values will *not* change. Implementation in 1014b879e9474a27b6c998e04af431e27cf1d0bf. Will merge to master if testing is successful.
