### ISSUE TITLE
Allow user to set up training elevation in user options screen

### ISSUE THREAD

**Issue by vladn2012** [ibooij/big-ring#58]
Currently speed is calculated based on sea level air density. This can possibly result in slower perceived speed for those who live on elevation since they normally ride in lower air density - lower FTP on elevation is balanced out by lower air pressure. Use user elevation air density value to calculate speed.

**Comment by ibooij** [comment]
I guess we should use the elevation from the RLV to determine air density.

**Comment by vladn2012** [comment]
That's not going to fix it - my FTP on 6K feet is 270w, when I go to sea level I should expect about 7% FTP boost into 290w: http://www.joefrielsblog.com/2010/09/altitude-and-aerobic-performance.html
This extra power will allow me to overcome higher air density at sea level and maintain speeds comparable to elevation. If you use air density from RLV, when I ride a trainer on 6K elevation and ride a course at sea level, I don't get FTP boost, yet get a higher air density hit resulting in slower perceived speed. 

If you use air density based on elevation from RLV, then you need to adjust FTP as well when calculating speed (based on Joe Friel table).

**Comment by ibooij** [comment]
I had not thought of it in that way. I live at about sea level, maybe a meter below, so it's quite different for me!

So we're talking about two different things:
* The user should be able to correct his (virtual) power output if his/her real altitude is above sea level.
* The virtual air density, used for speed calculations, should corrected using the virtual altitude (in the RLV).

Does this make sense?

**Comment by vladn2012** [comment]
You learn a lot about yourself when you live on elevation :)

This is the way I see it. In real life, rider is essentially carrying with him his elevation profile. If you were to come to ride in Denver @6K, you'll get hit with about 10% decrease in your FTP yet your speed will remain the same as you will benefit from lower air density. 

When rider sets his training elevation in Bing-Ring there are 2 options:

1. Do not adjust power and calculate speed based on air density of the elevation set up by user in elevation profile.
2. Do dynamic speed calculation. Adjust power and calculate speed based on elevation value from RLV. This obviously is more complicated to implement and I am not sure if it will result in any better result. In any case, you should adjust power only for speed calculation, not what you display to user. This implementation is also potentially problematic due to incorrect elevation data in RLV file, I think instead of real elevation it only has elevation profile.

So, the easy fix for now is option 1 - instead of using sea level value for air density, allow user to set up his training elevation and use it instead. This way we can test if our assumptions as correct. I can ride a course at 6K and then at 0 and see which one will correspond more closely to my real riding at 6K !

**Comment by ibooij** [comment]
I could try to implement your option 1 on a branch and hand you a build to test it. Or even make it simpler and give you a build in which you can just set a multiplier for your power. Then you can compare speed values.
That probably is not suited for an official release, but it might help to find out how to get this right.

**Comment by pajakgdynia** [comment]
AIR_DENSITY is used in the equation. So only it must be corrected according to current altitude.
But the question is, whether less oxygen affects result less than density.
I did notice.. that lower pressure has rather negative influence. But I live at the seaside as well :D

**Comment by vladn2012** [comment]
Ilja, if you can implement option 1 that would be great - I am ready to put it through some testing, thanks !

**Comment by vladn2012** [comment]
Jarek, yes AIR_DENSITY is used in the equation, but which value should it be ? If you ride a certain course home at 0 elevation at 20mph - then you decide to come and check out how cool Colorado/Denver is and stop by my house and check out my new and shiny Tacx Neo :) Then you ride the same course and see your avg speed drop by 10% while you exert the same effort. So, which avg is correct: 20 or 18mph ? By travelling to elevation you just broke the balance between FTP and AIR_DENSITY - it does not happen in real life because you will experience both drop in FTP as well as AIR_DENSITY. But if you had an option to set your training elevation to 6K feet, then your ride will be close to avg you got at home. Hope it makes sense :) Cheers !

**Comment by pajakgdynia** [comment]
Yes, it makes. I've just caught your idea.
Such correction is simple. Just a set of parameters in the config and function to get proper value.
But there is a lot of questions.. What about temperature and pressure. CdA is more "remarkable" (I ride recumbents, mostly low-racers, so I aerodynamic drag should be lower).
As far as I know, FE-C profile allows to set CdA&AirDensity (as one value), and Crr (rolling resistance). All such settings must be considered "how, when and where".
Keep in mind.. that trainers have only "some" accuracy (differences are up to 20-30%!)

**Comment by ibooij** [comment]
For me there's one very important thing to remember: Configuration for the average user should be kept as simple as possible!

It's quite easy to add features like this. It is hard to make them easy to use and it is (almost) impossible to remove them. So let's think hard and creatively about how we can elevation "correction".

The point about different drag factors for other types of bike should be in a different issue IMHO and be solved independently. The actual implementation might overlap of course

**Comment by vladn2012** [comment]
Keep it simple, add an extra box ('Training elevation') in user setting, default 0, allow user to change it and use this value in speed calculation. User always has an option not to use it (keep default 0), so there is no need to remove. 

If, in the future, you want to make it more "realistic" (such as adjusting user FTP and using air density based on real elevation), you would still need this box because I'll need to know user FTP and elevation for this FTP. Say my FTP is 270w on 6K elevation, yours is 400w on 0 elevation. When riding at 3K, you'll need to subtract your FTP and add mine, so this elevation box is probably going to stay !

I agree on separating bike profiles into different issue, perhaps add type of bike (road, TT, recumbent, mountain, tandem) when you set up a trainer profile.

**Comment by pajakgdynia** [comment]
In BR there's no need to add FTP (neither trainings with power, nor display in '%'). The riding speed depends only on weight (user "properties", I mean)
In my opinion, there should be two groups of settings: "general", and "advanced". Something like in VLC (video player). I've already discussed it with Ilja.

**Comment by ibooij** [comment]
Implemented in 1014b879e9474a27b6c998e04af431e27cf1d0bf (feature/simulation_user_settings branch) in an even simpler way. As each rider has a different reaction to altitude, the value is implemented as simple percentage. The rider can add 0%-25% to his/her power output in this way.

Perhaps the 25% value is a bit much.

**Comment by ibooij** [comment]
From Vlad:

1. Never touch/change power displayed to user - my power reading is single most important value to me, no matter what virtual elevation, etc. We should never change it !
2. Introduce new user setting - training elevation. Default 0, let user decide if they want to use this adjustment. Currently speed is calculated based on 0 elevation air density, instead use user 'training elevation' setting to calculate air resistance. Let's give it a shot and see how it works, you shouldn't see any difference, I should. My current average speed is about 5-10% lower than what I get with real riding outside.
3. Once we are past first stage of 'training elevation' testing, we can take it further, such as calculating speed based on adjusted power/air density for ride elevation. Regardless, we need to know user 'training elevation' in order to do that, so it will not be a wasted effort !

**Comment by ibooij** [comment]
Updated feature/simulation_user_settings branch to use the changed power in the simulation, but keep showing the original.

**Comment by ibooij** [comment]
Closed for now. Elevation setting is just a power percentage to apply (extra) to power in simulation. Let's test this first before doing real elevation/density calculations.
