### ISSUE TITLE
GPS export data looks jagged

### ISSUE THREAD

**Issue by vladn2012** [ibooij/big-ring#60]
If you zoom into GPS track from BR export, GPS data looks jagged (back and forth) instead of being smooth. Screenshot attached.
![gps data](https://cloud.githubusercontent.com/assets/16737836/12383560/df75e872-bd64-11e5-96e2-ea150e78a6ae.png)

**Comment by ibooij** [comment]
I think I might have made a stupid mistake interpolating between positions. Will investigate and make a fix.

**Comment by ibooij** [comment]
Fix is released in version 1.6.1, ready for download.

**Comment by vladn2012** [comment]
Re-tested - works perfectly, thanks :)
