### ISSUE TITLE
GPX data is not imported for ride

### ISSUE THREAD

**Issue by vladn2012** [ibooij/big-ring#61]
Some rides that have GPX files are imported with no 'complete distance' duplicate. Attached are 3 GPX files with issue - they seem to be well formed.

[GPX Files.zip](https://github.com/ibooij/big-ring/files/95145/GPX.Files.zip)

**Comment by ibooij** [comment]
I don't think the names for these files are the same as the names of the AVI files.

For instance, West.gpx should be IS_West.gpx. GPX files are matched to avi files by their filename, as there is no filename mentioned in the GPX file itself.

Is this the case? Do they import ok when filenames are changed?

**Comment by vladn2012** [comment]
Just tested and indeed the file name was the issue - once renamed to IS_West.gpx the GPX ride is successfully created. Closed.
