### ISSUE TITLE
Keep native aspect ratio/resolution when playing video

### ISSUE THREAD

**Issue by vladn2012** [ibooij/big-ring#64]
UK rides (available here:https://www.mediafire.com/folder/p6ihb0uxj2flc/RLV#wgcdr49z3qef2) are recorded in 1920x640 resolution. When video is played in BR, it is stretched vertically from 640 to 1280 and most of the image is cut out on left/right side. This stretch (essentially zoom) creates very poor quality of video with lots of artifacts visible and playback is not smooth. I think we should preserve original aspect ratio/resolution with black bars displayed on top and bottom. Another option is set user preference in settings, checkbox 'Keep original aspect ratio', yes/no. Screenshot of video with black bars in original resolution attached.

![native resolution with black bars](https://cloud.githubusercontent.com/assets/16737836/12439968/e9807978-bef3-11e5-9670-d908af20f601.jpg)

**Comment by ibooij** [comment]
Ah yes, I saw this as well.

Luckily, it's quite easy to do this. We already use [Qt::AspectRatioMode](https://doc.qt.io/qt-5/qt.html#AspectRatioMode-enum) to paint, so it will be quite easy to do this.

I always like it best when the video takes up the whole screen, so for me it would be best to make this a configuration option.

In addition, we could make it possible to change 'aspect ratio' on the fly, during a ride.

**Comment by vladn2012** [comment]
Great, thanks !

**Comment by ibooij** [comment]
This is now configurable from Preferences->Videos. Defaults to old behaviour, cutting off parts of the video left-right or above-below.

**Comment by ibooij** [comment]
Forgot to add some screenshots.

Configuration:
![configure aspect ratio](https://cloud.githubusercontent.com/assets/420742/12475062/69768d16-c020-11e5-92a7-d552fba41361.png)

Riding:
![running_full_video](https://cloud.githubusercontent.com/assets/420742/12475118/cd3f678c-c020-11e5-888a-367bb1248f97.png)

**Comment by vladn2012** [comment]
Looks nice ! Do you think it might be possible to make video "sit" on top of the bottom elevation profile control ? This way we will get more full screen feeling. This obviously will only be needed when image height is less then 80% or so of user screen resolution. You also mentioned the option to change 'aspect ratio' on the fly, during a ride. Did you have a chance to do it ?

**Comment by ibooij** [comment]
The picture is always centered now. It's a good idea to have it fit on top of the profile and other elements if that fits.

I'm thinking of redoing the ride screen, to make it easier to move elements around and change these kind of things.

I did not get a chance to change it on the fly yet.
