### ISSUE TITLE
Enable H.265 codec support

### ISSUE THREAD

**Issue by vladn2012** [ibooij/big-ring#71]
Video file encoded with H.265 codec in AVI container causes program to crash. It appears libav has to be compiled with H.265 --enable-libx265 configure option.

https://wiki.libav.org/Encoding/hevc

**Comment by vladn2012** [comment]
Uploaded US_DeerCreek_AVI_h265.avi video that can be used for testing (AVI container, H.265 codec)

**Comment by ibooij** [comment]
H265 works using our private code now.
