### ISSUE TITLE
Paint grades above 13% in dark red or purple in elevation profile

### ISSUE THREAD

**Issue by vladn2012** [ibooij/big-ring#72]
Grades from 7-9% are painted in orange, everything above 10% is red. Difficult to say if climb is going to stay in 10-11% or go to 14-15% range as the color remains the same. If extreme grades above 13% are painted in dark red or purple, it will give a better profile picture.

**Comment by ibooij** [comment]
Currently, the colors are taken from the HSV color space. 12% is Hue 0 (zero), which is red, -12% is hue 240 (blue). We could use the value between 300 and 360 for anything above 12%. @vladn2012 would you be able to experiment with this? The code is in `generalgui/profilepainter.cpp`, in the `colorForSlope(slope)` function.

**Comment by vladn2012** [comment]
Sure, I'll do it.
